// Blog post metadata
export const blogPosts = [
  {
    slug: 'what-are-calories',
    title: 'What Are Calories? A Complete Guide to Calorie Tracking',
    excerpt: 'Learn what calories actually are, how calorie tracking works, and why it\'s the most effective method for weight management.',
    category: 'Guides',
    readTime: 5,
    emoji: '⚡',
    image: 'calories-guide.webp',
    date: '2026-02-25',
    keywords: ['what are calories', 'calorie tracking', 'how calorie tracking works', 'calories explained'],
  },
  {
    slug: 'what-are-macros',
    title: 'What Are Macros? Understanding Macronutrients',
    excerpt: 'Learn what macronutrients (protein, carbs, and fat) are, what they do in your body, and why tracking them matters.',
    category: 'Guides',
    readTime: 5,
    emoji: '🍎',
    image: 'macros-guide.webp',
    date: '2026-02-25',
    keywords: ['what are macros', 'macronutrients explained', 'protein carbs fat', 'why track macros'],
  },
  {
    slug: 'how-to-calculate-tdee',
    title: 'How to Calculate Your TDEE (Total Daily Energy Expenditure)',
    excerpt: 'Learn how to calculate your TDEE using the Mifflin-St Jeor equation and understand what it means for your calorie goals.',
    category: ['Guides', 'Calculators'],
    readTime: 7,
    emoji: '🔥',
    image: 'tdee-calculator.webp',
    date: '2026-02-25',
    keywords: ['TDEE calculator', 'how to calculate TDEE', 'what is TDEE', 'total daily energy expenditure'],
  },
  {
    slug: 'best-blenders-for-protein-shakes',
    title: 'NutriBullet Pro 900 Review: 2 Years of Daily Use',
    excerpt: 'My honest review of the NutriBullet Pro 900 after using it daily for 2+ years to make protein shakes and smoothies.',
    category: 'Gear Reviews',
    readTime: 6,
    emoji: '🫐',
    image: 'nutribullet-pro-900.webp',
    date: '2026-02-25',
    keywords: ['NutriBullet Pro 900 review', 'best blender for protein shakes', 'smoothie blender review', 'NutriBullet review'],
  },
  {
    slug: 'macro-calculator-guide',
    title: 'Macro Calculator: Find Your Protein, Carbs, and Fat Goals',
    excerpt: 'Use our free macro calculator to find your optimal protein, carbohydrate, and fat intake based on your goals.',
    category: ['Guides', 'Calculators'],
    readTime: 6,
    emoji: '🧮',
    image: 'macro-calculator.webp',
    date: '2026-02-25',
    keywords: ['macro calculator', 'how to calculate macros', 'macros for weight loss', 'protein carbs fat ratio'],
  },
  {
    slug: 'best-adjustable-dumbbells-beginners',
    title: 'Best Adjustable Dumbbells for Beginners and Intermediate Lifters',
    excerpt: 'My review of the Core Fitness Adjustable Dumbbells—the perfect space-saving weight set with a twist-to-select mechanism (5-50 lbs).',
    category: 'Gear Reviews',
    readTime: 5,
    emoji: '🏋️',
    image: 'core-fitness-dumbbells.webp',
    date: '2026-02-26',
    keywords: ['best adjustable dumbbells', 'adjustable dumbbells review', 'Core Fitness dumbbells', 'home gym dumbbells', 'space saving dumbbells'],
  },
  {
    slug: 'best-adjustable-dumbbells-advanced',
    title: 'Best Adjustable Dumbbells for Intermediate to Advanced Lifters',
    excerpt: 'The best heavy-duty adjustable dumbbells that go up to 80 lbs—perfect for serious lifters who need more weight.',
    category: 'Gear Reviews',
    readTime: 5,
    emoji: '💪',
    image: 'nuobell-dumbbells.webp',
    date: '2026-02-26',
    keywords: ['best heavy dumbbells', 'adjustable dumbbells 80 lbs', 'advanced adjustable dumbbells', 'heavy duty dumbbells', 'home gym equipment'],
  },
];
